services:
  pet-radar:
    image: pet-radar:latest
    container_name: PetRadarAPI
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SERVICE: ${MAILER_SERVICE}
      APPINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis:16-master
    container_name: postgresDBPetRadar
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_db:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: redisPetRadar
    ports:
      - 6379:6379

volumes:
  postgres_data_db: